import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-main',
  templateUrl: './main.component.html',
  styleUrl: './main.component.scss',
})
export class MainComponent implements OnInit {
  displayedColumns: any[] = [
    {
      key: 'name',
      name: 'Məzmun',
    },
    {
      key: 'brand',
      name: 'Məzmun',
    },
    {
      key: 'plantNumber',
      name: 'Məzmun',
    },
    {
      key: 'plantNumberInsp',
      name: 'Məzmun',
    },
    {
      key: 'factoryNumber',
      name: 'Məzmun',
    },
    {
      key: 'count',
      name: 'Məzmun',
    },
    {
      key: 'plantPredmet',
      name: 'Məzmun',
    },
    {
      key: 'serialNumber',
      name: 'Məzmun',
    },
    {
      key: 'inventoryNumber',
      name: 'Məzmun',
    },
    {
      key: 'serialNumber',
      name: 'Məzmun',
    },
    {
      key: 'inventoryNumber',
      name: 'Məzmun',
    },
    {
      key: 'plantStateNumber',
      name: 'Məzmun',
    },
    {
      key: 'plantType',
      name: 'Məzmun',
    },
    {
      key: 'mainInspectorTypeName',
      name: 'Məzmun',
    },
    {
      key: 'dangerObjectName',
      name: 'Məzmun',
    },
    {
      key: 'dangerObjectPersonName',
      name: 'Məzmun',
    },
    {
      key: 'mainPersonName',
      name: 'Məzmun',
    },
    {
      key: 'note',
      name: 'Məzmun',
    },
  ];

  dataSource = [
    {
      id: 46,
      name: 'Sərnişin lifti',
      brand: 'Tamaslift',
      plantNumber: 'A-16311-01',
      plantNumberInsp: '27/122-QL',
      factoryNumber: 'zav.№ 2204-29060',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'zav.№ 2204-29060',
      inventoryNumber: 'zav.№ 2204-29060',
      plantStateNumber: '-',
      plantType: 'Stasionar / Sərnişin lifti',
      mainInspectorTypeName:
        '11 / Qazan, qaldırıcı və energetika qurğularında işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Tibb müəssisəsi.',
      dangerObjectPersonName: 'ƏHMƏDOV VÜQAR İLQAR',
      mainPersonName: 'ƏHMƏDOV VÜQAR İLQAR',
      note: '-',
      plantTechIdentificators: [
        {
          value: '630',
          plantUnitType: 'kq',
        },
      ],
    },
    {
      id: 45,
      name: 'İki dirəkli qaldırıcı qurğu',
      brand: 'MAT-2934',
      plantNumber: 'A-16239-01',
      plantNumberInsp: '-',
      factoryNumber: 'İnv№ 03',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'İnv№ 03',
      inventoryNumber: 'İnv№ 03',
      plantStateNumber: '-',
      plantType:
        'Avtonəqliyyat vasitələrinin qaldırılması üçün xüsusi quraşdırılmış qaldırıcı qurğular (3.)',
      mainInspectorTypeName:
        '16 / Təhlükə potensiallı sənaye avadanlıqlarının istehsalında və emal sənayesində işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Avtomobil təmiri sahəsi',
      dangerObjectPersonName: 'CƏFƏROV QƏHRƏMAN ASİF',
      mainPersonName: 'CƏFƏROV QƏHRƏMAN ASİF',
      note: '-',
      plantTechIdentificators: [
        {
          value: '4000',
          plantUnitType: 'kq',
        },
      ],
    },
    {
      id: 44,
      name: 'SƏMƏDOV FİZULİ ƏLEYVAZ',
      brand: 'Sepli yelləncək',
      plantNumber: 'A-10563-02',
      plantNumberInsp: '0066',
      factoryNumber: 'zav.485692',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'zav.485692',
      inventoryNumber: 'zav.485692',
      plantStateNumber: '-',
      plantType: 'Stasionar / Mexanikləşdirilmiş attraksion',
      mainInspectorTypeName: 'Qeydiyyatdan çıxarılıb',
      dangerObjectName: 'Attraksion (Xətai r-nu)',
      dangerObjectPersonName: 'SƏMƏDOV FİZULİ ƏLEYVAZ',
      mainPersonName: 'SƏMƏDOV FİZULİ ƏLEYVAZ',
      note: 'Attraksion parkın bağlanması səbəbindən sökülmüş və hal-hazırda istismar edilmir (məktub №3-18-3/1-S-2717-42/24, 25.09.2024)',
      plantTechIdentificators: [
        {
          value: '12',
          plantUnitType: 'nəfərlik',
        },
      ],
    },
    {
      id: 42,
      name: '1 №-li Yeraltı polad çən',
      brand: 'ÜPÇ',
      plantNumber: 'A-16212-228',
      plantNumberInsp: '-',
      factoryNumber: 'Sap kodu: 2000247',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'Sap kodu: 2000247',
      inventoryNumber: 'Sap kodu: 2000247',
      plantStateNumber: '-',
      plantType: 'Neft yığım çəni (mərkəzi neft yığım məntəqəsi)',
      mainInspectorTypeName:
        '22 / Magistral boru kəmərlərində işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName:
        'İxrac istehsalat bölümü, Şirvanlı ixrac neft təhvili sahəsi',
      dangerObjectPersonName: 'NEFT KƏMƏRLƏRİ İDARƏSİ',
      mainPersonName: 'NEFT KƏMƏRLƏRİ İDARƏSİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '8',
          plantUnitType: 'kub.metr',
        },
      ],
    },
    {
      id: 41,
      name: 'Dizel çəni',
      brand: 'ÜPÇ',
      plantNumber: 'A-16212-229',
      plantNumberInsp: '-',
      factoryNumber: 'Sap kodu:7008939',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'Sap kodu:7008939',
      inventoryNumber: 'Sap kodu:7008939',
      plantStateNumber: '-',
      plantType: 'Neft yığım çəni (mərkəzi neft yığım məntəqəsi)',
      mainInspectorTypeName:
        '22 / Magistral boru kəmərlərində işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName:
        'İxrac istehsalat bölümü, Şirvanlı ixrac neft təhvili sahəsi',
      dangerObjectPersonName: 'NEFT KƏMƏRLƏRİ İDARƏSİ',
      mainPersonName: 'NEFT KƏMƏRLƏRİ İDARƏSİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '1',
          plantUnitType: 'kub.metr',
        },
      ],
    },
    {
      id: 40,
      name: 'Yeraltı drenaj çəni',
      brand: 'ŞPÇ',
      plantNumber: 'A-16212-230',
      plantNumberInsp: '-',
      factoryNumber: 'Sap kodu:3000541',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'Sap kodu:3000541',
      inventoryNumber: 'Sap kodu:3000541',
      plantStateNumber: '-',
      plantType: 'Neft yığım çəni (mərkəzi neft yığım məntəqəsi)',
      mainInspectorTypeName:
        '22 / Magistral boru kəmərlərində işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName:
        'İxrac istehsalat bölümü, Şirvanlı ixrac neft təhvili sahəsi',
      dangerObjectPersonName: 'NEFT KƏMƏRLƏRİ İDARƏSİ',
      mainPersonName: 'NEFT KƏMƏRLƏRİ İDARƏSİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '2',
          plantUnitType: 'kub.metr',
        },
      ],
    },
    {
      id: 39,
      name: '110 KV-luq 1-ci və 2-ci Mərkəz hava xətləri',
      brand: 'AS-185 Metal,D/B (50 dayaq)',
      plantNumber: '-',
      plantNumberInsp: '-',
      factoryNumber: '111020045675',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '111020045675',
      inventoryNumber: '111020045675',
      plantStateNumber: '-',
      plantType: 'Yüksəkgərginlikli elektrik xətləri və qurğuları',
      mainInspectorTypeName: 'Qeydiyyatdan keçirilməyib',
      dangerObjectName: 'Gəncə EŞ',
      dangerObjectPersonName: 'AZƏRİŞIQ AÇIQ SƏHMDAR CƏMİYYƏTİ',
      mainPersonName: 'AZƏRİŞIQ AÇIQ SƏHMDAR CƏMİYYƏTİ',
      note: 'Qərb RETSİ',
      plantTechIdentificators: [
        {
          value: '8.6+8.6',
          plantUnitType: 'km',
        },
        {
          value: '110',
          plantUnitType: 'Kvt',
        },
      ],
    },
    {
      id: 38,
      name: 'Sərnişin lifti',
      brand: 'SİGMA',
      plantNumber: 'A-16258-02',
      plantNumberInsp: 'S/29068',
      factoryNumber: 'zav.№ 2014C0012E01',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'zav.№ 2014C0012E01',
      inventoryNumber: 'zav.№ 2014C0012E01',
      plantStateNumber: '-',
      plantType: 'Stasionar / Sərnişin lifti',
      mainInspectorTypeName:
        '29 / Cənub regional SİTG və Dağ-Mədən Nəzarəti müfətişliyi',
      dangerObjectName: 'Cəzaçəkmə müəssiəsi',
      dangerObjectPersonName: 'ƏDLİYYƏ NAZİRLİYİNİN PENTENSİAR XİDMƏTİ',
      mainPersonName: 'ƏDLİYYƏ NAZİRLİYİNİN PENTENSİAR XİDMƏTİ',
      note: '---',
      plantTechIdentificators: [
        {
          value: '450',
          plantUnitType: 'kq',
        },
      ],
    },
    {
      id: 37,
      name: 'Bir tirli mexaniki tal',
      brand: '(əl ilə idarə olunan)',
      plantNumber: 'A-16212-231',
      plantNumberInsp: '-',
      factoryNumber: 'Sap kodu: 15000403',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'Sap kodu: 15000403',
      inventoryNumber: 'Sap kodu: 15000403',
      plantStateNumber: '-',
      plantType: 'Xüsusi qaldırıcı qurğu',
      mainInspectorTypeName:
        '22 / Magistral boru kəmərlərində işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName:
        'İxrac istehsalat bölümü, Şirvanlı ixrac neft təhvili sahəsi',
      dangerObjectPersonName: 'NEFT KƏMƏRLƏRİ İDARƏSİ',
      mainPersonName: 'NEFT KƏMƏRLƏRİ İDARƏSİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '3.2',
          plantUnitType: 'ton',
        },
      ],
    },
    {
      id: 36,
      name: '110 KV-luq 1-ci və 2-ci 8 KM hava xətlərindən Radiozavod budaqlanmaları',
      brand: 'AS-120 Metal D/B, (21 dayaq)',
      plantNumber: '-',
      plantNumberInsp: '-',
      factoryNumber: '111020001152',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '111020001152',
      inventoryNumber: '111020001152',
      plantStateNumber: '-',
      plantType: 'Yüksəkgərginlikli elektrik xətləri və qurğuları',
      mainInspectorTypeName: 'Qeydiyyatdan keçirilməyib',
      dangerObjectName: 'Bakı-Xətai EŞ',
      dangerObjectPersonName: 'AZƏRİŞIQ AÇIQ SƏHMDAR CƏMİYYƏTİ',
      mainPersonName: 'AZƏRİŞIQ AÇIQ SƏHMDAR CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '2.3+2.3',
          plantUnitType: 'km',
        },
        {
          value: '110',
          plantUnitType: 'Kvt',
        },
      ],
    },
    {
      id: 35,
      name: '110 KV-luq 2-ci Ağstafa hava xətlərindən Qovlar budaqlanmaları',
      brand: 'AS-120 Metal (1 dayaq)',
      plantNumber: '-',
      plantNumberInsp: '-',
      factoryNumber: '111030079156',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '111030079156',
      inventoryNumber: '111030079156',
      plantStateNumber: '-',
      plantType: 'Yüksəkgərginlikli elektrik xətləri və qurğuları',
      mainInspectorTypeName: 'Qeydiyyatdan keçirilməyib',
      dangerObjectName: 'Tovuz EŞ',
      dangerObjectPersonName: 'AZƏRİŞIQ AÇIQ SƏHMDAR CƏMİYYƏTİ',
      mainPersonName: 'AZƏRİŞIQ AÇIQ SƏHMDAR CƏMİYYƏTİ',
      note: 'Qərb RETSİ',
      plantTechIdentificators: [
        {
          value: '0.2',
          plantUnitType: 'km',
        },
        {
          value: '110',
          plantUnitType: 'Kvt',
        },
      ],
    },
    {
      id: 34,
      name: '110 KV-luq 1-ci və 2-ci Ağstafa hava xətlərindən Tovuz budaqlanmaları',
      brand: 'AS-120 Metal (1 dayaq)',
      plantNumber: '-',
      plantNumberInsp: '-',
      factoryNumber: '111030079171',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '111030079171',
      inventoryNumber: '111030079171',
      plantStateNumber: '-',
      plantType: 'Yüksəkgərginlikli elektrik xətləri və qurğuları',
      mainInspectorTypeName: 'Qeydiyyatdan keçirilməyib',
      dangerObjectName: 'Tovuz EŞ',
      dangerObjectPersonName: 'AZƏRİŞIQ AÇIQ SƏHMDAR CƏMİYYƏTİ',
      mainPersonName: 'AZƏRİŞIQ AÇIQ SƏHMDAR CƏMİYYƏTİ',
      note: 'Qərb RETSİ',
      plantTechIdentificators: [
        {
          value: '0.2+0.2',
          plantUnitType: 'km',
        },
        {
          value: '110',
          plantUnitType: 'Kvt',
        },
      ],
    },
    {
      id: 33,
      name: 'Çəngəlli yükləyici',
      brand: 'Heli CPCD30',
      plantNumber: 'AZ 004882',
      plantNumberInsp: '-',
      factoryNumber: 'mühərrik № C490BPG23063612 şassi № 010303C2554',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'mühərrik № C490BPG23063612 şassi № 010303C2554',
      inventoryNumber: 'mühərrik № C490BPG23063612 şassi № 010303C2554',
      plantStateNumber: '110-FA-246',
      plantType: 'Yükləyicilər (frontal, çəngəlağız, çalovlu, teleskopik)',
      mainInspectorTypeName:
        '20 / Texnoloji nəqliyyat vasitələrində işlərin təhlükəsiz görülməsinə nəzarət müfətişliyi',
      dangerObjectName: 'Təh. yük. dəmir yolu nəqliy. ilə daşın. sahəsi',
      dangerObjectPersonName:
        'AZƏRBAYCAN DƏMİR YOLLARI QAPALI SƏHMDAR CƏMİYYƏTİ',
      mainPersonName: 'AZƏRBAYCAN DƏMİR YOLLARI QAPALI SƏHMDAR CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '-',
          plantUnitType: '--',
        },
      ],
    },
    {
      id: 32,
      name: 'Elektrik Körpülü Kran',
      brand: 'BVS',
      plantNumber: 'A-13704-14',
      plantNumberInsp: '17454',
      factoryNumber: 'Seriya № 2872-06',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'Seriya № 2872-06',
      inventoryNumber: 'Seriya № 2872-06',
      plantStateNumber: '-',
      plantType: 'Stasionar / Körpülü kran',
      mainInspectorTypeName:
        '24 / Sumqayıt regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: 'İstehsalat Sahələri (Dəqiq mexanika zavodu)',
      dangerObjectPersonName: 'SOCAR-STP MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      mainPersonName: 'SOCAR-STP MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '25',
          plantUnitType: 'ton',
        },
        {
          value: '22760',
          plantUnitType: 'mm',
        },
      ],
    },
    {
      id: 31,
      name: '110 KV-luq 1-ci və 2-ci Yasamal hava xətləri',
      brand: 'AS-300 Metal (15 dayaq)',
      plantNumber: '-',
      plantNumberInsp: '-',
      factoryNumber: '111020001179',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '111020001179',
      inventoryNumber: '111020001179',
      plantStateNumber: '-',
      plantType: 'Yüksəkgərginlikli elektrik xətləri və qurğuları',
      mainInspectorTypeName: 'Qeydiyyatdan keçirilməyib',
      dangerObjectName: 'Bakı-Yasamal EŞ',
      dangerObjectPersonName: 'AZƏRİŞIQ AÇIQ SƏHMDAR CƏMİYYƏTİ',
      mainPersonName: 'AZƏRİŞIQ AÇIQ SƏHMDAR CƏMİYYƏTİ',
      note: 'BAKI RETSİ',
      plantTechIdentificators: [
        {
          value: '1.7+1.7',
          plantUnitType: 'km',
        },
        {
          value: '110',
          plantUnitType: 'Kvt',
        },
      ],
    },
    {
      id: 30,
      name: 'Elektrik Körpülü Kran',
      brand: 'BVS',
      plantNumber: 'A-13704-12',
      plantNumberInsp: '17462',
      factoryNumber: 'Seriya № GH20.09.0026',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'Seriya № GH20.09.0026',
      inventoryNumber: 'Seriya № GH20.09.0026',
      plantStateNumber: '-',
      plantType: 'Stasionar / Körpülü kran',
      mainInspectorTypeName:
        '24 / Sumqayıt regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: 'İstehsalat Sahələri (Dəqiq mexanika zavodu)',
      dangerObjectPersonName: 'SOCAR-STP MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      mainPersonName: 'SOCAR-STP MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '16',
          plantUnitType: 'ton',
        },
        {
          value: '28550',
          plantUnitType: 'mm',
        },
      ],
    },
    {
      id: 29,
      name: 'Yanacaq çəni',
      brand: 'Dördkünc',
      plantNumber: 'A-15646-03',
      plantNumberInsp: '-',
      factoryNumber: 'Çən №1',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'Çən №1',
      inventoryNumber: 'Çən №1',
      plantStateNumber: '-',
      plantType: 'Yanacaq çəni (YDM)',
      mainInspectorTypeName:
        '26 / Qərb regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: 'Yanacaq doldurma məntəqəsi',
      dangerObjectPersonName: 'LUKOIL ŞİRKƏTİ',
      mainPersonName: 'LUKOIL ŞİRKƏTİ',
      note: '',
      plantTechIdentificators: [
        {
          value: '5.6',
          plantUnitType: 'kub.metr',
        },
      ],
    },
    {
      id: 28,
      name: 'Təbii qaz xətti',
      brand: 'FORNAVA GAS',
      plantNumber: 'A-15383-681',
      plantNumberInsp: '-',
      factoryNumber: '0',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '0',
      inventoryNumber: '0',
      plantStateNumber: '-',
      plantType: 'Qaz kəməri',
      mainInspectorTypeName:
        '12 / Maye və təbii qaz obyektlərində işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Sıxılmış təbii qaz sahəsi (Zığ şossesi)',
      dangerObjectPersonName: 'SOCAR PETROLEUM QAPALI SƏHMDAR CƏMİYYƏTİ',
      mainPersonName: 'SOCAR PETROLEUM QAPALI SƏHMDAR CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '219',
          plantUnitType: 'mm',
        },
        {
          value: '6000',
          plantUnitType: 'metr',
        },
      ],
    },
    {
      id: 27,
      name: 'Yanacaq çəni',
      brand: 'Dördkünc',
      plantNumber: 'A-15646-04',
      plantNumberInsp: '-',
      factoryNumber: 'Çən №2',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'Çən №2',
      inventoryNumber: 'Çən №2',
      plantStateNumber: '-',
      plantType: 'Yanacaq çəni (YDM)',
      mainInspectorTypeName:
        '26 / Qərb regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: 'Yanacaq doldurma məntəqəsi',
      dangerObjectPersonName: 'LUKOIL ŞİRKƏTİ',
      mainPersonName: 'LUKOIL ŞİRKƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '5.6',
          plantUnitType: 'kub.metr',
        },
      ],
    },
    {
      id: 26,
      name: 'Qaz tənzimləyici',
      brand: 'RDO-1-100/10',
      plantNumber: 'A-15383-682',
      plantNumberInsp: '-',
      factoryNumber: '0',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '0',
      inventoryNumber: '0',
      plantStateNumber: '-',
      plantType: 'Qaz tənzimləyici qurğusu',
      mainInspectorTypeName:
        '12 / Maye və təbii qaz obyektlərində işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Sıxılmış təbii qaz sahəsi (Zığ şossesi)',
      dangerObjectPersonName: 'SOCAR PETROLEUM QAPALI SƏHMDAR CƏMİYYƏTİ',
      mainPersonName: 'SOCAR PETROLEUM QAPALI SƏHMDAR CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '10',
          plantUnitType: 'MPa',
        },
      ],
    },
    {
      id: 25,
      name: 'Yanacaq çəni',
      brand: 'Horizontal silindirik',
      plantNumber: 'A-15646-06',
      plantNumberInsp: '-',
      factoryNumber: 'Çən №4',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'Çən №4',
      inventoryNumber: 'Çən №4',
      plantStateNumber: '-',
      plantType: 'Yanacaq çəni (YDM)',
      mainInspectorTypeName:
        '26 / Qərb regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: 'Yanacaq doldurma məntəqəsi',
      dangerObjectPersonName: 'LUKOIL ŞİRKƏTİ',
      mainPersonName: 'LUKOIL ŞİRKƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '-',
          plantUnitType: 'ton',
        },
      ],
    },
    {
      id: 24,
      name: 'Kompressor qurğu kompleksi',
      brand: 'FORNAVA GAS',
      plantNumber: 'A-15383-683',
      plantNumberInsp: '-',
      factoryNumber: 'zavod № 2259PG001',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'zavod № 2259PG001',
      inventoryNumber: 'zavod № 2259PG001',
      plantStateNumber: '-',
      plantType: 'Kompressor.',
      mainInspectorTypeName:
        '12 / Maye və təbii qaz obyektlərində işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Sıxılmış təbii qaz sahəsi (Zığ şossesi)',
      dangerObjectPersonName: 'SOCAR PETROLEUM QAPALI SƏHMDAR CƏMİYYƏTİ',
      mainPersonName: 'SOCAR PETROLEUM QAPALI SƏHMDAR CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '275',
          plantUnitType: 'Bar',
        },
      ],
    },
    {
      id: 23,
      name: 'Silo',
      brand: 'Dürdabanlı',
      plantNumber: 'A-16141-06',
      plantNumberInsp: '-',
      factoryNumber: '№S6',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '№S6',
      inventoryNumber: '№S6',
      plantStateNumber: '-',
      plantType: 'Taxıl silosu',
      mainInspectorTypeName:
        '31 / Şimal-qərb regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: 'Toxum emalı zavodu',
      dangerObjectPersonName: 'DÖVLƏT TOXUM FONDU',
      mainPersonName: 'test',
      note: '',
      plantTechIdentificators: [
        {
          value: '600',
          plantUnitType: 'ton',
        },
      ],
    },
    {
      id: 22,
      name: 'Bitum çəni',
      brand: 'Silindrik polad',
      plantNumber: 'A-10129-07',
      plantNumberInsp: '-',
      factoryNumber: 't',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '-',
      inventoryNumber: '-',
      plantStateNumber: '-',
      plantType: 'Bitum çəni (asfalt istehsalı)',
      mainInspectorTypeName:
        '27 / Qarabağ regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: 'Asfalt istehsalı sahəsi',
      dangerObjectPersonName: 'YOL İNŞAAT SERVİS MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      mainPersonName: 'YOL İNŞAAT SERVİS MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '0',
          plantUnitType: 'ton',
        },
      ],
    },
    {
      id: 21,
      name: 'Aspirasiya qurğusu',
      brand: 'Uğur Makina',
      plantNumber: 'A-16256-114',
      plantNumberInsp: '-',
      factoryNumber: 'İnv №1',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'İnv №1',
      inventoryNumber: 'İnv №1',
      plantStateNumber: '-',
      plantType: 'Taxılın saxlanması və təmizlənməsi qurğusu',
      mainInspectorTypeName:
        '26 / Qərb regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: 'Taxıl saxlama anbarı(Bakı)',
      dangerObjectPersonName:
        'AZƏRBAYCAN DÖVLƏT EHTİYATLARI AGENTLİYİ PUBLİK HÜQUQİ ŞƏXSİ',
      mainPersonName:
        'AZƏRBAYCAN DÖVLƏT EHTİYATLARI AGENTLİYİ PUBLİK HÜQUQİ ŞƏXSİ',
      note: '/',
      plantTechIdentificators: [
        {
          value: '2769',
          plantUnitType: 'kub.m/saat',
        },
      ],
    },
    {
      id: 20,
      name: 'Mazut çəni',
      brand: 'Silindrik polad',
      plantNumber: 'A-10129-08',
      plantNumberInsp: '-',
      factoryNumber: '0',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '0',
      inventoryNumber: '0',
      plantStateNumber: '-',
      plantType: 'Mazut çəni (asfalt istehsalı)',
      mainInspectorTypeName:
        '27 / Qarabağ regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: 'Asfalt istehsalı sahəsi',
      dangerObjectPersonName: 'YOL İNŞAAT SERVİS MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      mainPersonName: 'YOL İNŞAAT SERVİS MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      note: '',
      plantTechIdentificators: [
        {
          value: '0',
          plantUnitType: 'metr',
        },
      ],
    },
    {
      id: 19,
      name: 'Qaz paylayıcı kolonka',
      brand: 'FORNAVA GAS',
      plantNumber: 'A-15383-686',
      plantNumberInsp: '-',
      factoryNumber: 'Zav№ 2260PE002',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'Zav№ 2260PE002',
      inventoryNumber: 'Zav№ 2260PE002',
      plantStateNumber: '-',
      plantType: 'Təbii qaz paylayıcı kalonka',
      mainInspectorTypeName:
        '12 / Maye və təbii qaz obyektlərində işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Sıxılmış təbii qaz sahəsi (Zığ şossesi)',
      dangerObjectPersonName: 'SOCAR PETROLEUM QAPALI SƏHMDAR CƏMİYYƏTİ',
      mainPersonName: 'SOCAR PETROLEUM QAPALI SƏHMDAR CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '1.5-12',
          plantUnitType: 'kq/dəqiqə',
        },
      ],
    },
    {
      id: 18,
      name: 'Yanacaq çəni',
      brand: 'Polad',
      plantNumber: 'A-16052-662',
      plantNumberInsp: '-',
      factoryNumber: '0',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '0',
      inventoryNumber: '0',
      plantStateNumber: '-',
      plantType: 'Yanacaq çəni (YDM)',
      mainInspectorTypeName:
        '27 / Qarabağ regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: '"Ağcabədi" YDM',
      dangerObjectPersonName: 'AZPETROL LTD MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      mainPersonName: 'AZPETROL LTD MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '61.255',
          plantUnitType: 'ton',
        },
      ],
    },
    {
      id: 17,
      name: 'Yanacaq çəni',
      brand: 'Polad',
      plantNumber: 'A-16052-663',
      plantNumberInsp: '-',
      factoryNumber: '-',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '-',
      inventoryNumber: '-',
      plantStateNumber: '-',
      plantType: 'Yanacaq çəni (YDM)',
      mainInspectorTypeName:
        '27 / Qarabağ regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: '"Ağcabədi" YDM',
      dangerObjectPersonName: 'AZPETROL LTD MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      mainPersonName: 'AZPETROL LTD MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '73.054',
          plantUnitType: 'ton',
        },
      ],
    },
    {
      id: 16,
      name: 'Sərnişin lifti',
      brand: 'HYUNDAİ ELEVATOR',
      plantNumber: 'A-16342-01',
      plantNumberInsp: '42879',
      factoryNumber: 'zav.№ T19504L01',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'zav.№ T19504L01',
      inventoryNumber: 'zav.№ T19504L01',
      plantStateNumber: '-',
      plantType: 'Stasionar / Sərnişin lifti',
      mainInspectorTypeName:
        '11 / Qazan, qaldırıcı və energetika qurğularında işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Tibb müəssisəsi',
      dangerObjectPersonName:
        'İNTERNATİONAL MEDİCAL CENTRE MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      mainPersonName:
        'İNTERNATİONAL MEDİCAL CENTRE MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '1600',
          plantUnitType: 'kq',
        },
      ],
    },
    {
      id: 15,
      name: 'Yanacaq çəni',
      brand: 'Polad',
      plantNumber: 'A-16052-664',
      plantNumberInsp: '-',
      factoryNumber: '-',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '-',
      inventoryNumber: '-',
      plantStateNumber: '-',
      plantType: 'Yanacaq çəni (YDM)',
      mainInspectorTypeName:
        '27 / Qarabağ regional SİTG və Dağ-Mədən Nəzarəti müfəttişliyi',
      dangerObjectName: '"Ağcabədi" YDM',
      dangerObjectPersonName: 'AZPETROL LTD MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      mainPersonName: 'AZPETROL LTD MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '73.124',
          plantUnitType: 'ton',
        },
      ],
    },
    {
      id: 14,
      name: 'Su qızdırıcı qazan',
      brand: 'Azikaran',
      plantNumber: 'A-15753-660',
      plantNumberInsp: 'ASK-2-1000',
      factoryNumber: '№ 96501',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '№ 96501',
      inventoryNumber: '№ 96501',
      plantStateNumber: '-',
      plantType: 'Su qızdırıcı qazan',
      mainInspectorTypeName:
        '11 / Qazan, qaldırıcı və energetika qurğularında işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Wyndham Garden Baku otel',
      dangerObjectPersonName: 'AZPETROL LTD MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      mainPersonName: 'AZPETROL LTD MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '116.2',
          plantUnitType: 'Kw',
        },
      ],
    },
    {
      id: 13,
      name: 'Sərnişin-yük lifti',
      brand: 'PW21/16-19',
      plantNumber: 'A-12031-288',
      plantNumberInsp: '40901',
      factoryNumber: 'zav: 4230987',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'zav: 4230987',
      inventoryNumber: 'zav: 4230987',
      plantStateNumber: '-',
      plantType: 'Stasionar / Sərnişin lifti',
      mainInspectorTypeName:
        '11 / Qazan, qaldırıcı və energetika qurğularında işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Dəniz Mall ticarət mərkəzi',
      dangerObjectPersonName: 'PAŞA MALLS MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      mainPersonName: 'PAŞA MALLS MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '1600',
          plantUnitType: 'kq',
        },
      ],
    },
    {
      id: 12,
      name: 'Qaldırıcı qurğu',
      brand: 'JCPT212',
      plantNumber: 'A-16339-06',
      plantNumberInsp: '44382',
      factoryNumber: 'zav.№ İnv.№04',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: 'zav.№ İnv.№04',
      inventoryNumber: 'zav.№ İnv.№04',
      plantStateNumber: '-',
      plantType: 'Xüsusi qaldırıcı qurğu',
      mainInspectorTypeName:
        '11 / Qazan, qaldırıcı və energetika qurğularında işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Dəniz Mall ticarət mərkəzi',
      dangerObjectPersonName: 'PAŞA MALLS MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      mainPersonName: 'PAŞA MALLS MƏHDUD MƏSULİYYƏTLİ CƏMİYYƏTİ',
      note: '-',
      plantTechIdentificators: [
        {
          value: '320',
          plantUnitType: 'kq',
        },
      ],
    },
    {
      id: 11,
      name: 'Reaktor',
      brand: 'R-24',
      plantNumber: 'A-16218-02',
      plantNumberInsp: '199/N',
      factoryNumber: '30005',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '30005',
      inventoryNumber: '30005',
      plantStateNumber: '-',
      plantType: 'Reaktor',
      mainInspectorTypeName:
        '14 / Kimya, neftkimya və neftqaz emalı sənayesində işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Metanol istehsalı sahəsi',
      dangerObjectPersonName:
        'AZƏRBAYCAN RESPUBLİKASININ DÖVLƏT NEFT ŞİRKƏTİNİN METANOL ZAVODU',
      mainPersonName:
        'AZƏRBAYCAN RESPUBLİKASININ DÖVLƏT NEFT ŞİRKƏTİNİN METANOL ZAVODU',
      note: '-',
      plantTechIdentificators: [
        {
          value: '150300',
          plantUnitType: 'litr',
        },
      ],
    },
    {
      id: 10,
      name: 'Qaz filtr seperatoru',
      brand: 'ФСГ-СН-300/200-63-120000-0,08-ДГ-ИЭ-2000',
      plantNumber: 'A-16218-71',
      plantNumberInsp: '-',
      factoryNumber: '0',
      count: 1,
      plantPredmet: 'ədəd',
      serialNumber: '0',
      inventoryNumber: '0',
      plantStateNumber: '-',
      plantType: 'Qaz seperatoru',
      mainInspectorTypeName:
        '14 / Kimya, neftkimya və neftqaz emalı sənayesində işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Metanol istehsalı sahəsi',
      dangerObjectPersonName:
        'AZƏRBAYCAN RESPUBLİKASININ DÖVLƏT NEFT ŞİRKƏTİNİN METANOL ZAVODU',
      mainPersonName:
        'AZƏRBAYCAN RESPUBLİKASININ DÖVLƏT NEFT ŞİRKƏTİNİN METANOL ZAVODU',
      note: '-',
      plantTechIdentificators: [
        {
          value: '6,3',
          plantUnitType: 'kq/kvad.sm',
        },
      ],
    },
    {
      id: 9,
      name: 'Körpülü kran',
      brand: 'PKK-10',
      plantNumber: 'A-16218-75',
      plantNumberInsp: '-',
      factoryNumber: 'zav.№ 45090',
      count: 1,
      plantPredmet: '.',
      serialNumber: 'zav.№ 45090',
      inventoryNumber: 'zav.№ 45090',
      plantStateNumber: '-',
      plantType: 'Stasionar / Körpülü kran',
      mainInspectorTypeName:
        '11 / Qazan, qaldırıcı və energetika qurğularında işlərin təhlükəsiz görülməsinə nəzarət müfəttişliyi',
      dangerObjectName: 'Metanol istehsalı sahəsi',
      dangerObjectPersonName:
        'AZƏRBAYCAN RESPUBLİKASININ DÖVLƏT NEFT ŞİRKƏTİNİN METANOL ZAVODU',
      mainPersonName:
        'AZƏRBAYCAN RESPUBLİKASININ DÖVLƏT NEFT ŞİRKƏTİNİN METANOL ZAVODU',
      note: '.',
      plantTechIdentificators: [
        {
          value: '10',
          plantUnitType: 'ton',
        },
      ],
    },
    {
      id: 6,
      name: 'test',
      brand: 'test',
      plantNumber: '424',
      plantNumberInsp: '535',
      factoryNumber: '4343',
      count: 24,
      plantPredmet: 'dəst',
      serialNumber: '4322',
      inventoryNumber: '42',
      plantStateNumber: '34',
      plantType: 'Stasionar / Portal kran',
      mainInspectorTypeName: 'Qeydiyyatdan keçirilməyib',
      dangerObjectName: null,
      dangerObjectPersonName: null,
      mainPersonName: 'AĞAMURADOV ƏDALƏT MƏDƏD',
      note: '',
      plantTechIdentificators: [
        {
          value: '23',
          plantUnitType: 'metr',
        },
      ],
    },
  ];

  ngOnInit(): void {
    console.log('sadad', this.dataSource);
  }
}
